CC := g++
CFLAGS := --std=c++11 -Wall -c
LFLAGS := --std=c++11
SRC := src
BIN := bin
DOC := doc

all: $(BIN)/freq

.PHONY: clean doc test

# generates readable documentation
doc:
	doxygen doxyfile

# runs the test cases generated by TXE
test:
	test.sh

$(BIN)/freq: freq.o
	$(CC) $(LFLAGS) freq.o -o $(BIN)/freq

freq.o: $(SRC)/most_freq.cpp
	$(CC) $(CFLAGS) $(SRC)/most_freq.cpp -o freq.o

clean:
	rm -rf *.o $(BIN)/* $(DOC)/*

